### ISSUE TITLE
ImportError for clock

### ISSUE THREAD

**Issue by banzsolt** [infinnovation/piwall-cvtools#3]
ImportError: cannot import name 'clock'
https://github.com/infinnovation/piwall-cvtools/blob/master/model.py#L42

Should this be:
`from time import clock`

or is there another common file in your /samples/python folder that is missing from the project?  
The clock module is not used anywhere in the code so that line can even be removed

**Comment by infinnovation-dev** [comment]
I agree - poor practice on my part here.  I was pulling in the opencv/samples/python/common module.
